name: Docker Image to GHCR

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install dependencies and update lockfile
      - name: Install pipenv and update dependencies
        run: |
          python -m pip install --upgrade pip pipenv
          pipenv lock --requirements > requirements.txt
          pipenv lock

      # Step 4: Set up QEMU for cross-platform builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Step 5: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 6: Log in to GitHub Container Registry (GHCR)
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 7: Build and push WSGI server Docker image
      - name: Build and push WSGI Server
        uses: docker/build-push-action@v4
        with:
          context: .
          target: wsgi-server
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/chatgpt-ui-wsgi-server:latest
            ghcr.io/${{ github.repository_owner }}/chatgpt-ui-wsgi-server:${{ github.ref_name }}

      # Step 8: Build and push Web server Docker image
      - name: Build and push Web Server
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/chatgpt-ui-web-server:latest
            ghcr.io/${{ github.repository_owner }}/chatgpt-ui-web-server:${{ github.ref_name }}
